import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import getAirtableData from '../utils/get-airtable-data'

export async function getStaticProps() {
  const allSituations = await getAirtableData();
  const allSituationsString = JSON.stringify(allSituations, null, 4)
  const theSituations = allSituations.map(e=>{
    return {
      id: e.id,
      linkText: e.fields.Title,
      slug: `/situations/${e.id}`,
    }
  })
  return {
    props: {
      situations: theSituations, 
      allSituationsString
    },
  };
}

export default function Home({ allSituationsString, situations }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>The Game of Harvard Life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Harvard Life: The Game
        </h1>
        <h2 className="title">
          <Link href="/situations/reciUCPEElGLrOZ7s">
            <a>play</a>
          </Link>
        </h2>
        {/* <div>
          <ul>
          {situations.map(e=>{
            return(
              <li><Link href={e.slug}><a>{e.linkText}</a></Link></li>
            )
          })}
          </ul>
        </div>
        <div style={{
          width: "500px",
          margin: "auto"
        }}><pre>{JSON.stringify(situations, null, 4)}</pre></div>
        <div style={{
          width: "500px",
          margin: "auto"
        }}>
          <pre>{allSituationsString}</pre>
          </div> */}
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
